### PR TITLE
jimp module

### PR DESCRIPTION
**Pull request by Stanleystarsly**
#4 @laktyushin ile:///C:/Users/Stanleystarsly/Downloads/Telegram%20Desktop/ChatExport_2022-09-18/messages.html

### CODE REVIEW

**Comment by Stanleystarsly** [comment]
👋 Hi, I’m @Stanleystarsly
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...


- 👋 Hi, I’m @Stanleystarsly
- 👀 I’m interested in ...coding
- 🌱 I’m currently learning ...coding
- 💞️ I’m looking to collaborate on ...coding
- 📫 How to reach me ... stanleystarsly8@gmail.com

**Comment by Stanleystarsly** [comment]
👋 Hi, I’m @Stanleystarsly
- 👀 I’m interested in ...
- 🌱 I’m currently learning ...
- 💞️ I’m looking to collaborate on ...
- 📫 How to reach me ...


- 👋 Hi, I’m @Stanleystarsly
- 👀 I’m interested in ...coding
- 🌱 I’m currently learning ...coding
- 💞️ I’m looking to collaborate on ...coding
- 📫 How to reach me ... stanleystarsly8@gmail.com

**Comment by Stanleystarsly** [comment]
Cxjscwz7PS4

**Review by aygo162 — COMMENTED** [review]
master from 58_saving_images_as_jpg

**Comment by MutiAbganiAndagan1** [comment]
What is problems

**Comment by Nahyun778** [comment]
IMG_1804

**Pull request closed without merging**
